product: ucc
release: "1.0"
scope: ucs_3.1-0-ucc-errata
src: univention-ucc-printerconfig
fix: 1.0.0-1.1.201307181224
note:
desc: |
  univention-ucc-printerconfig allows to configure cups servers with
  the UCR variable ucc/cups/server.
version: [0]
bug: [31902]
