product: ucc
release: "1.0"
scope: ucs_3.1-0-ucc-errata
src: univention-ucc-proxy-settings
fix: 1.0.0-5.5.201309261523
note:
desc: |
  The firefox proxy settings are now forced with
  'lockPref' in the firefox configuration file.
version: [0]
bug: [32580]
