product: ucc
release: "2.0"
scope: ucs_3.2-0-ucc20-errata
src: univention-ucc-firefox-config
fix: 1.0.0-2.2.201506170957
note:
desc: |
  The package univention-ucc-firefox-config has been added to
  set firefox user preferences via UCR ucc/firefox/defaults/
  in /usr/lib/firefox/defaults/pref/ucc-prefs.js.
version: [0]
bug: [37774]
